# Generated by Django 3.1.1 on 2021-10-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0002_auto_20211014_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
