# Generated by Django 3.1.1 on 2021-10-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0003_admin_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=500)),
                ('hint', models.CharField(max_length=500)),
                ('photo', models.ImageField(blank=True, upload_to='media/')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qrcodes/'),
        ),
    ]
