# Generated by Django 3.1.1 on 2021-10-19 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0004_auto_20211014_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='media/')),
                ('uploader_id', models.IntegerField()),
                ('uploaded_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='folder_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
