# Generated by Django 3.1.1 on 2021-10-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0011_auto_20211028_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='changepass',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
