# Generated by Django 3.1.1 on 2021-10-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0012_auto_20211028_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='changepass',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
