# Generated by Django 3.1.1 on 2021-10-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0016_auto_20211028_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
