# Generated by Django 3.1.1 on 2021-10-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0017_auto_20211028_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='documents',
            name='updated_at',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='documents',
            name='uploaded_at',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='changepass',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
