# Generated by Django 3.1.1 on 2021-10-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0019_documents_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='changename',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
