# Generated by Django 3.1.1 on 2021-10-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0020_documents_changename'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='trace_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
