# Generated by Django 3.1.1 on 2021-11-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0021_documents_trace_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField()),
                ('docname', models.CharField(max_length=255)),
                ('traceid', models.BigIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('received_on', models.CharField(blank=True, max_length=50)),
                ('send_on', models.CharField(blank=True, max_length=50)),
                ('sender', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
