# Generated by Django 3.1.1 on 2021-11-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0022_sharedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='receiver_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
