# Generated by Django 3.1.1 on 2021-11-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0023_auto_20211101_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='sender_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
