# Generated by Django 3.1.1 on 2021-11-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0024_sharedfile_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='last_status',
            field=models.CharField(default='sdf', max_length=255),
            preserve_default=False,
        ),
    ]
