# Generated by Django 3.1.1 on 2021-11-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0025_documents_last_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='changename',
        ),
    ]
