# Generated by Django 3.1.1 on 2021-11-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0026_remove_documents_changename'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='doc_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
