# Generated by Django 3.1.1 on 2021-11-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0027_sharedfile_doc_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField()),
                ('notified_id', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecentActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField()),
                ('notified_id', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ADD', 'fas fa-plus'), ('DELETE', 'fas fa-trash'), ('INOUT', 'bx bx-log-out'), ('UPDATE', 'fas fa-edit')], max_length=50)),
            ],
        ),
    ]
