# Generated by Django 3.1.1 on 2021-11-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0028_notification_recentactivities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivities',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
