# Generated by Django 3.1.1 on 2021-11-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0029_auto_20211106_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentactivities',
            old_name='category',
            new_name='class_style',
        ),
    ]
