# Generated by Django 3.1.1 on 2021-11-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0030_auto_20211106_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
