# Generated by Django 3.1.1 on 2021-11-07 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0032_auto_20211107_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='trace_id',
        ),
    ]
