# Generated by Django 3.1.1 on 2021-11-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0033_remove_notification_trace_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
