# Generated by Django 3.1.1 on 2021-11-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0034_doctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='folder_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qr_code',
        ),
    ]
