# Generated by Django 3.1.1 on 2021-11-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0035_auto_20211108_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentactivities',
            name='class_style',
        ),
    ]
