# Generated by Django 3.1.1 on 2021-11-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0036_remove_recentactivities_class_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tracenumber',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
