# Generated by Django 3.1.1 on 2021-11-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0038_auto_20211108_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tracenumber',
            field=models.IntegerField(default=0),
        ),
    ]
