# Generated by Django 3.1.1 on 2021-11-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0039_auto_20211108_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='comment',
            field=models.TextField(default='sd'),
            preserve_default=False,
        ),
    ]
