# Generated by Django 3.1.1 on 2021-11-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0040_sharedfile_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='ownqr_code',
            field=models.ImageField(blank=True, upload_to='qrcodes/'),
        ),
    ]
