# Generated by Django 3.2.9 on 2021-11-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evsudts', '0041_sharedfile_ownqr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documents',
            name='qr_code',
            field=models.ImageField(upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documents',
            name='updated_at',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documents',
            name='uploaded_at',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='doc_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='ownqr_code',
            field=models.ImageField(upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='received_on',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='receiver_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='send_on',
            field=models.CharField(max_length=50),
        ),
    ]
